FROM cybera/jsp-zeek

WORKDIR /tmp

RUN apt update \
    && apt install linux-headers-$(uname -r) \
    && zkg autoconfig \
    && zkg install --force \
       zeek-af_packet-plugin \
       zeek-sniffpass \
       zeek-httpattacks \
    # Cleanup
    && rm -rf /tmp/* \
    && rm -rf /var/lib/apt/lists/*

COPY files/etc/* /opt/zeek/etc/
COPY files/init.sh /init.sh
COPY files/local.zeek* /opt/zeek/share/zeek/site/

VOLUME /opt/zeek/logs
VOLUME /opt/zeek/spool


CMD ["/init.sh"]
